version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

commands:
jobs:
  lint-docker-file:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < react-application/Dockerfile

  build-docker:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t capstone-devops ./react-application
      - run:
          name: Add tagging
          command: docker tag capstone-devops lqtoan20/capstone-devops:v1
      - run:
          name: Login Docker hub
          command: docker login -u lqtoan20 -p $DOCKERPASS
      - run:
          name: Push image
          command: docker push lqtoan20/capstone-devops:v1

workflows:
  default:
    jobs:
      - lint-docker-file
      - build-docker:
          requires: [lint-docker-file]
