version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

commands:
jobs:
  lint-docker-file:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

  build-docker:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t capstone-devops ./react-application
            docker tag capstone-devops lqtoan20/capstone-devops:v1
            docker login -u lqtoan20 -p $DOCKERPASS
            docker push lqtoan20/capstone-devops:v1

workflows:
  default:
    jobs:
      - lint-docker-file
      - build-docker:
          requires: [lint-docker-file]
