apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  namespace: default
  labels:
    app: capstone-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app-deployment
  template:
    metadata:
      labels:
        app: capstone-app-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: capstone-app-deployment
          image: lqtoan20/capstone-devops:v1
          ports:
            - name: tcp
              containerPort: 5000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-deployment
  namespace: default
  labels:
    app: capstone-app-deployment
spec:
  selector:
    app: capstone-app-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
