apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: default
  labels:
    app: capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: capstone-app
          image: lqtoan20/capstone-devops:v1
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  selector:
    app: capstone-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
