apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  progressDeadlineSeconds: 3600
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - image: lqtoan20/capstone-devops:v1
          imagePullPolicy: Always
          name: capstone-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
